<?php

//error_reporting(E_ALL ^ E_NOTICE);

function bank_menu() {

    $items['bank/form-bank'] = array(
      'title' => 'Example Bank Form',
      'description' => 'A bank form to mess around with.',
      'page callback' => 'my_call',
      'access arguments' => array('user1')
    );
    $items['bank/edit/%'] = array(
      'title' => 'Edit Bank Form ',
      'description' => 'A bank form to eit the details.',
      'page callback' => 'my_call',
      'access callback' => TRUE
    );
    $items['bank/view/%'] = array(
      'title' => 'View Bank Form ',
      'description' => 'A bank form to eit the details.',
      'page callback' => 'my_call1',
      'access callback' => TRUE
    );
    $items['bank/viewall'] = array(
      'title' => 'View all the Bank Form ',
      'description' => 'A bank form to eit the details.',
      'page callback' => 'my_call2',
      'access arguments' => array('viewall')
    );
    return $items;
}

function bank_permission() {
    return array(
      'user1' => array(
        'title' => t('user permission'),
        'description' => t('giving permission to user'),
      ),
      'viewall' => array(
        'title' => t('Viewall permission'),
        'description' => t('Viewall to user'),
      ),
    );
}

function my_call() {
    return drupal_get_form('bank_form');
}

function my_call1() {
    $path = arg(2);
    global $user;
    $result = db_select('bank')
        ->fields('bank', array('name', 'banknumber', 'comments'))
        ->condition('id', $path, '=')
        ->execute()
        ->fetchAssoc();
    $header = array(t('Name'), t('Number'), t('comments'));
    $op = "name " . $result['name'] . "<br/>" . " number " . $result['banknumber'] . "<br/>" . " comments " . $result['comments'];
    return $op;
}

function my_call2() {
    
    global $base_url;
    $header = array('id' => array('data' => 'Id', 'field' => 'bank.id'),
      'name' => array('data' => 'Name', 'field' => 'bank.name'),
      'edit' => array('data' => 'Edit'),
      'view' => array('data' => 'View'));
    $query = db_select('bank')
        ->fields('bank', array('id', 'name', 'banknumber', 'comments'))
        ->execute()
        ->fetchAll();
    foreach($query as $key => $value){
        $rows[$value->id]['id'] = $value->id;
        $rows[$value->id]['name'] = $value->name;
        $rows[$value->id]['edit'] = "<a href='" . $base_url . "/bank/edit/".$value->id."'>edit</a>";
        $rows[$value->id]['view'] = "<a href='" . $base_url . "/bank/view/".$value->id."'>View</a>";
        
    }
    


    $output .= theme('table', array('header' => $header, 'rows' => $rows));

    return $output;
}

function bank_form($form, &$form_state) {

$form['title'] = array(
          '#type' => 'textfield',
          '#title' => t('Name'),
          '#required' => TRUE,
        );
        $form['number'] = array(
          '#type' => 'textfield',
          '#title' => t('Bank Number'),
          '#maxlength' => 128,
          '#required' => TRUE,
        );
        $form['pass'] = array(
          '#type' => 'password',
          '#title' => t('Password'),
          '#maxlength' => 64,
          '#size' => 15,
          '#required' => TRUE,
        );

        $form['keywords'] = array(
          '#title' => t('comments'),
          '#type' => 'textarea',
        );
        $form['submit_button'] = array(
          '#type' => 'submit',
          '#value' => t('Save!'),
        );



    if (arg(1) == "edit") {
        $path = arg(2);


        $result = db_select('bank')
            ->fields('bank')
            ->condition('id', $path, '=')
            ->execute()
            ->fetchAssoc();

        $form['title']['#default_value'] = $result['name'];
        $form['number']['#default_value'] = $result['banknumber'];
        $form['pass']['#default_value'] = $com;
        $form['keywords']['#default_value'] = $result['comments'];
        
       
       
    }
     return $form;
}

function bank_form_validate($form, &$form_state) {
    
}

function bank_form_submit($form, &$form_state) {




    if (arg(1) == "form-bank") {
        global $user;
        $date = new DateTime();
        $d1 = $date->format('Y-m-d H:i:s');
        db_insert('bank')
            ->fields(array(
              'name' => $form_state['values']['title'],
              'banknumber' => $form_state['values']['number'],
              'password' => $form_state['values']['pass'],
              'comments' => $form_state['values']['keywords'],
              'modifiedby' => $user->uid,
              'modifiedon' => $d1,
              'createdon' => $d1,
              'createdby' => $user->uid
            ))
            ->execute();
    }
    else if (arg(1) == "edit") {
        $date = new DateTime();
        $d1 = $date->format('Y-m-d H:i:s');
        $num_updated = db_update('bank')
            ->fields(array(
              'name' => $form_state['values']['title'],
              'banknumber' => $form_state['values']['number'],
              'password' => $form_state['values']['pass'],
              'comments' => $form_state['values']['keywords'],
              'modifiedby' => $user->uid,
              'modifiedon' => $d1,
            ))
            ->condition('id', arg(2), '=')
            ->execute();
    }
}

?>